afterflask/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
import django.contrib.auth.views as auth
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/v1/', include('clean.api.urls', namespace='api_clean')),
    url(r'', include('clean.urls', namespace='clean')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

clean/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
from . import models

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^company/$', views.CompanyView.as_view(), name='company'),
    url(r'^leave-feedback/$', views.LeaveFeedbackView.as_view(), name='leave-feedback'),
    url(r'^technicians/$', views.TechnicianListView.as_view(), name='technicians'),
    url(r'^technicians/(?P<pk>\d+)/$', views.TechnicianDetailView.as_view(), name='technician'),
    url(r'^jobs/$', views.JobListView.as_view(), name='jobs'),
    url(r'^jobs/(?P<pk>\d+)/$', views.JobDetailView.as_view(), name='job'),
    url(r'^feedback/$', views.FeedbackListView.as_view(), name='feedbacks'),
    url(r'^feedback/(?P<pk>\d+)/$', views.FeedbackDetailView.as_view(), name='feedback'),
]

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en" ng-app="cleanApp">
<head>
    <meta charset="UTF-8"/>
    <title>Naturalcare Cleaning Reviews | {% block title %}{% endblock %}</title>

    <!-- meta -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <meta name="author" content="Brandon Rumiser - Phoenix Coding"/>
    <meta name="theme-color" content="#F54311">
    <meta name="msapplication-navbutton-color" content="#F54311">
    <meta name="apple-mobile-web-app-status-bar-style" content="#F54311">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <!-- /meta -->

    <!-- favicons -->
    <link rel="shortcut icon" href="/static/ico/favicon.png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="/static/ico/favicon.png">
    <!-- /favicons -->

    <script>
        var messages = [];
        {% if messages %}
            {% for message in messages %}
                messages.push({
                    type: 'danger',
                    msg: "{{ message }}",
                    timeout: 5000
                });
            {% endfor %}
        {% endif %}
        {% if form.errors.items %}
            {% for field, errors in form.errors.items %}
                {% for error in errors %}
                    messages.push({
                        type: 'danger',
                        msg: "{{ field }}: {{ error }}"
                    });
                {% endfor %}
            {% endfor %}
        {% endif %}
    </script>
    <style>
        .block {
            display: block;
            position: absolute;
            background: rgba(255, 255, 255, 1);
            z-index: 99999;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }
    </style>
    {% block header_script %}{% endblock %}

</head>

<body ng-controller="reviewsController" id="page-top" class="body {% block body_class %}{% endblock %}">

{% block menu %}
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" ng-click="isNavCollapsed = !isNavCollapsed">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'clean:home' %}">Naturalcare</a>
            </div>
            <div class="collapse navbar-collapse" uib-collapse="isNavCollapsed">
                <ul class="nav navbar-nav">
                    {% if user.is_authenticated %}
                        <li {% if "company" in request.path %} class="active" {% endif %}>
                            <a href="{% url 'clean:company' %}">Company</a>
                        </li>
                        <li class="dropdown {% if "technicians" in request.path or "jobs" in request.path %} active {% endif %}"
                            uib-dropdown>
                            <a class="dropdown-toggle" uib-dropdown-toggle>Reports <b class="caret"></b></a>
                            <ul class="dropdown-menu" uib-dropdown-menu role="menu">
                                <li {% if "technicians" in request.path %} class="active" {% endif %}><a
                                        href="{% url 'clean:technicians' %}">Technicians</a></li>
                                <li {% if "jobs" in request.path %} class="active" {% endif %}><a
                                        href="{% url 'clean:jobs' %}">Jobs</a></li>
                                <li {% if "feedback" in request.path %} class="active" {% endif %}><a
                                        href="{% url 'clean:feedbacks' %}">Feedback</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_staff %}
                        <li><a href="{% url 'admin:login' %}">Admin</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li {% if "login" in request.path or "logout" in request.path %} class="active" {% endif %}>
                            <a href="{% url 'auth_logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li {% if "login" in request.path or "logout" in request.path %} class="active" {% endif %}>
                            <a href="{% url 'auth_login' %}">Login</a>
                        </li>
                    {% endif %}

                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
{% endblock %}

{% block header %}{% endblock %}

<!-- Begin page content -->
<main id="content" role="main">
    {% block messages %}
        <div class="container alerts" ng-show="alerts != ''">
            <div uib-alert ng-repeat="alert in alerts" ng-class="'alert-' + (alert.type || 'warning')"
                 dismiss-on-timeout="{$alert.timeout$}" close="closeAlert($index)">{$ alert.msg | filterHtmlChars $}
            </div>
        </div>
    {% endblock %}

    {% block content %}{% endblock %}
</main>


{% block footer %}
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h4><strong>Naturalcare Cleaning Services</strong>
                    </h4>
                    <p>3481 Melrose Place
                        <br>Beverly Hills, CA 90210</p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i> (123) 456-7890</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i> <a
                                href="mailto:name@example.com">name@example.com</a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="#"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-dribbble fa-fw fa-3x"></i></a>
                        </li>
                    </ul>
                    <hr class="small">
                    <p class="text-muted">&copy; {% now "Y" %} Naturalcare Cleaning Services</p>
                </div>
            </div>
        </div>
        <a id="to-top" href="#page-top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
    </footer>
{% endblock %}

<div class="loaderContainer" ng-hide="loaded">
    <div class="loader">Loading...</div>
</div>


<!-- styles -->
<link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet">
<link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.css" rel="stylesheet">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<link type="text/css" rel="stylesheet" href="/static/css/main.css"/>
<!-- /styles -->

<!--<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular-animate.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular-touch.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular-strap/2.3.9/angular-strap.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/2.2.0/ui-bootstrap-tpls.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.bundle.js"></script>
<script src="//cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.min.js"></script>

<script src="{% static 'js/smoothscroll.js' %}"></script>
<script src="{% static 'js/directives/ng-infinite-scroll.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
<script src="{% static 'js/controller-base.js' %}"></script>
{% block controllers %}{% endblock %}
{% block footer_scripts %}{% endblock %}

</body>
</html>